version: 2

builds:
  - id: glint
    main: ./cmd/glint
    binary: glint
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.FullCommit}}
      - -X main.buildTime={{.Date}}

dockers:
  - image_templates:
      - "ghcr.io/darshan-rambhia/glint:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/darshan-rambhia/glint:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/darshan-rambhia/glint:{{ .Version }}"
    image_templates:
      - "ghcr.io/darshan-rambhia/glint:{{ .Version }}-amd64"
      - "ghcr.io/darshan-rambhia/glint:{{ .Version }}-arm64"
  - name_template: "ghcr.io/darshan-rambhia/glint:latest"
    image_templates:
      - "ghcr.io/darshan-rambhia/glint:{{ .Version }}-amd64"
      - "ghcr.io/darshan-rambhia/glint:{{ .Version }}-arm64"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: darshan-rambhia
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/darshan-rambhia/glint"
    description: "Lightweight Proxmox monitoring dashboard"
    license: "MIT"
    dependencies:
      - name: sqlite
    install: |
      bin.install "glint"
    test: |
      assert_match version.to_s, shell_output("#{bin}/glint --version")

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
