version: '3'

tasks:
  generate:
    desc: Generate templ templates
    cmds:
      - templ generate

  build:
    desc: Build the glint binary
    deps: [generate]
    cmds:
      - CGO_ENABLED=1 go build -ldflags="-s -w" -o bin/glint ./cmd/glint

  dev:
    desc: Run glint with hot-reload (requires air — go install github.com/air-verse/air@latest)
    cmds:
      - air

  test:
    desc: Run tests with race detector, coverage tracking, and threshold enforcement
    cmds:
      - go run ./scripts/coverage

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - gofmt -w .
      - templ fmt .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/ target/
      - find . -name '*_templ.go' -delete

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t glint:dev .

  docker:run:
    desc: Run with Docker Compose
    cmds:
      - docker compose up -d

  swagger:
    desc: Generate Swagger/OpenAPI documentation
    cmds:
      - swag init -g cmd/glint/main.go -o docs/swagger

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod tidy
