name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure glint.yml with ...
        2. Run `glint --config glint.yml`
        3. Navigate to the dashboard
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or logs if available.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Glint Version
      description: Output of `glint --version` or the Docker image tag.
      placeholder: v0.1.0
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      options:
        - Docker / Docker Compose
        - Podman / Quadlet
        - Bare metal (systemd)
        - Homebrew
        - Built from source
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Host OS
      placeholder: Debian 12, Ubuntu 24.04, etc.
    validations:
      required: false

  - type: input
    id: pve-version
    attributes:
      label: Proxmox VE Version
      placeholder: "8.3"
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant portions of your `glint.yml` (redact credentials).
      render: yaml
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output. Run with `--log-level debug` for more detail.
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information.
    validations:
      required: false
