name: 'Go setup'
description: >
  Checkout, configure Go with module and build caching,
  install templ, and generate templates.

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: '1.26'
        cache: true        # caches GOMODCACHE + GOCACHE, keyed on go.sum

    - name: Install templ
      shell: bash
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: Generate templates
      shell: bash
      run: templ generate
